defaults:
    - _self_
    - environment: mujocoAnt.yaml
    - model: BO.yaml
    - datamodule: SoRoSim.yaml
    - paths: default.yaml
    - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
    - experiment: example.yaml
    - trainer: default.yaml

seed: null

ckpt_path: null
