defaults:
    - _self_
    - environment: mujocoAnt.yaml
    # - model: NN.yaml
    - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
    - experiment: example.yaml

seed: null
